# Site settings
title: BT5153 Applied Machine Learning for Business Analytics
email: diszr@nus.edu.sg
description: "Course webiste for BT5153"
#baseurl: ""
#url: ""
#github_username: ""
  
theme: jekyll-theme-minimal